jonasalden-travelplanner/Models/Trip.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace jonasalden_travelplanner.Models
{
    public class Trip
    {
        // Department
        public string DepId { get; set; }
        public string DepName { get; set; }
        public DateTime DepTime { get; set; }
        
        // Destination
        public string DestId { get; set; }
        public string DestName { get; set; }
        public string DestLon { get; set; }
        public string DestLat { get; set; }
        public DateTime DestTime { get; set; }

        // Weather
        public int Forecast { get; set; }
        public string ForecastName { get; set; }
        public decimal Celsius { get; set; }
    }
}

jonasalden-travelplanner/ViewModels/TicketsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using jonasalden_travelplanner.Models;

namespace jonasalden_travelplanner.ViewModels
{
    public class TicketsViewModel
    {
        [Required]
        public string DepName { get; set; }
        public DateTime DepTime { get; set; }

        public string DestId { get; set; }
        [Required]
        public string DestName { get; set; }
        public DateTime DestTime { get; set; }
        public string DestLon { get; set; }
        public string DestLat { get; set; }

        public decimal Celsius { get; set; }
        public string ForecastName { get; set; }
    }
}

jonasalden-travelplanner/Controllers/TravelsController.cs
using System;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Mvc;
using jonasalden_travelplanner.ViewModels;
using Newtonsoft.Json.Linq;

namespace jonasalden_travelplanner.Controllers
{
    public class TravelsController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            var model = new TicketsViewModel();
            model.DepName = "Örebro Centralstation";
            return View(model);
        }
        //GET: Travel

        [HttpPost]
        public async Task<ActionResult> Index(TicketsViewModel newTicket)
        {
            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    var response = await client.GetAsync("http://localhost:51901/api/travels/{destName}" + newTicket.DestName);
                    if (response.IsSuccessStatusCode)
                    {
                        var content = await response.Content.ReadAsStringAsync();
                        var json = JObject.Parse(content);
                        var ticket = new TicketsViewModel()
                        {
                            DepName = json["DepName"].Value<string>(),
                            DepTime = (DateTime)json["DepTime"],
                            DestName = json["DestName"].Value<string>(),
                            DestTime = (DateTime)json["DestTime"],
                            DestLon = json["DestLon"].Value<string>(),
                            DestLat = json["DestLat"].Value<string>(),
                            Celsius = json["Celsius"].Value<decimal>(),
                            ForecastName = json["ForecastName"].Value<string>()

                        };
                        return View(ticket);
                    }
                }
            }
            else
            {
                TempData["Message"] = "Destination can not be empty.";
                TempData["Type"] = "alert-danger";
                return RedirectToAction("Index");
            }
               return HttpNotFound();        
        }
    }
}

jonasalden-travelplanner/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Travels</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Travels</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

jonasalden-travelplanner/Views/Travels/Index.cshtml
@model jonasalden_travelplanner.ViewModels.TicketsViewModel
@{
    ViewBag.Title = "Index";
}
@if (TempData["Message"] != null)
{
<div class="row">
    <div class="alert @TempData["Type"]" role="alert">@TempData["Message"]</div>
</div>
}
@if (Model.DestName == null)
{
    <div class="col-md-12">
        @using (Html.BeginForm("Index", "Travels", FormMethod.Post))
        {
            <div class="row">
                <div class="col-md-6">
                    @Html.LabelFor(x => x.DepName, "Department")
                    @Html.TextBoxFor(x => x.DepName, new {@readonly = "readonly", @class = "form-control"})
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-6">
                    @Html.LabelFor(x => x.DestName, "Destination")
                    @Html.TextBoxFor(x => x.DestName, new { @class = "form-control", @pattern = "^[a-zåäöA-ZÅÄÖ 0-9]*$", @maxlength = 50})
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12" style="margin-top: 30px;">
                    <input type="submit" id="submitButton" class="btn btn-success" />
                </div>
            </div>
            <div class="clearfix"></div>
        }
    </div>
}
@if (Model.DestName != null)
{
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-12">
                <h1>Ticket Details</h1>
            </div>
            <table class="table table-sm">
                <thead>
                    <tr>
                        <th scope="col">From: @Model.DepName</th>
                        <th></th>
                        <th scope="col">To: @Model.DestName</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Depature time: @Model.DepTime</td>
                        <td></td>
                        <td>Arriving time: @Model.DestTime</td>
                    </tr>
                </tbody>
            </table>
            <div class="col-md-6">
                <span><b>Degrees:</b> @Model.Celsius°C</span>
            </div>
            <div class="col-md-6">
                <span><b>Forecast at destination:</b> @Model.ForecastName</span>
            </div>
        </div>
    </div>
}